In [19]:
import numpy as np
import pandas as pd
from adaptivenetworks.nnetwork import nnetwork

In [20]:
data = pd.read_csv("ml_prj_dataset.csv")

data.head()

powder  salt  oil  edible  vegetable  wheat  flour  sugar  chilli  red  \
0       1     1    1       1          1      0      1      0       1    1   
1       0     0    0       0          0      0      0      0       0    0   
2       0     0    0       0          0      0      0      0       0    0   
3       0     0    1       0          0      0      0      0       0    0   
4       0     0    0       0          0      0      0      0       0    0   

   ...  tocopheryl  triethanolamine  cl  titanium  dioxide  root  stearate  \
0  ...           0                0   0         0        0     0         0   
1  ...           0                0   0         0        0     0         0   
2  ...           0                0   0         0        0     0         0   
3  ...           0                0   0         0        0     0         0   
4  ...           0                0   0         0        0     0         0   

   orange  honey  TYPE  
0       0      0     0  
1       0      0     1  
2       0      0     1  
3       0      0     1  
4       0      0     1  

[5 rows x 114 columns]

In [21]:
data.describe()

powder        salt         oil      edible   vegetable       wheat  \
count  187.000000  187.000000  187.000000  187.000000  187.000000  187.000000   
mean     0.240642    0.320856    0.481283    0.229947    0.251337    0.208556   
std      0.428621    0.468059    0.500991    0.421928    0.434946    0.407367   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    1.000000    1.000000    0.000000    0.500000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

            flour       sugar      chilli         red  ...  tocopheryl  \
count  187.000000  187.000000  187.000000  187.000000  ...  187.000000   
mean     0.235294    0.224599    0.203209    0.171123  ...    0.053476   
std      0.425321    0.418438    0.403467    0.377627  ...    0.225585   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
50%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
75%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

       triethanolamine          cl    titanium     dioxide        root  \
count       187.000000  187.000000  187.000000  187.000000  187.000000   
mean          0.053476    0.010695    0.048128    0.042781    0.058824   
std           0.225585    0.103139    0.214612    0.202906    0.235926   
min           0.000000    0.000000    0.000000    0.000000    0.000000   
25%           0.000000    0.000000    0.000000    0.000000    0.000000   
50%           0.000000    0.000000    0.000000    0.000000    0.000000   
75%           0.000000    0.000000    0.000000    0.000000    0.000000   
max           1.000000    1.000000    1.000000    1.000000    1.000000   

         stearate      orange       honey        TYPE  
count  187.000000  187.000000  187.000000  187.000000  
mean     0.037433    0.048128    0.058824    0.524064  
std      0.190330    0.214612    0.235926    0.500761  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000    1.000000  
75%      0.000000    0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000    1.000000  

[8 rows x 114 columns]

In [22]:
data = np.array(data)
m, n = data.shape
print("m = " + str(m) + ", n = " + str(n))

m = 187, n = 114


In [23]:
split_ratio = 0.75

data_train = data[:int(m*split_ratio), :]
data_test = data[int(m*split_ratio):, :]
print("data_train.shape = " + str(data_train.shape))

print("data_test.shape = " + str(data_test.shape))

X_train = data_train[:, 0:n-1].T
Y_train = data_train[:, n-1]
X_test = data_test[:, 0:n-1].T
Y_test = data_test[:, n-1]


data_train.shape = (140, 114)
data_test.shape = (47, 114)


### Using input and output layer with no hidden layers

In [24]:
myn = nnetwork(113, 2, insertDefault=False ,learningRate=0.05)

In [25]:
# myn.forward_prop(input_values=np.zeros(113))
myn.forward_prop(input_values=X_train.T[30])
# myn.forward_prop(input_values=X_train.T[30])

array([[1.9322099 ],
       [0.57805523]])

In [26]:
myn.output_layer.weights.shape

(2, 113)

In [27]:
myn.output_layer.weights

array([[ 0.17576027,  0.12584528,  0.41712734, -0.41873679, -0.0239657 ,
        -0.40661519, -0.1155656 , -0.47483832, -0.25291873, -0.10402701,
        -0.1513087 ,  0.41713416,  0.35169556,  0.14810189, -0.41940541,
        -0.39088118,  0.10618661,  0.27495659, -0.31353846,  0.05885413,
         0.35885739,  0.35509614, -0.2144875 , -0.07963398,  0.11744041,
        -0.0771674 ,  0.00309145,  0.43626009,  0.39287381,  0.28601095,
        -0.17266099,  0.24595993,  0.19003903,  0.33790799, -0.07855008,
        -0.27269725, -0.2956351 ,  0.36339629, -0.1456029 ,  0.03635656,
        -0.32612996,  0.42041072,  0.40678625, -0.4390187 ,  0.25427817,
        -0.32500696, -0.46669292, -0.18739201, -0.35526249, -0.42325394,
         0.27060743, -0.28038394, -0.12636718, -0.06005911, -0.18440635,
        -0.3789649 , -0.05909097,  0.33883287, -0.01843789,  0.00760644,
         0.22843197,  0.31024526, -0.31006131, -0.42970735,  0.01385904,
        -0.35876523,  0.19537079, -0.07758074, -0.2

##### Backprop

In [28]:
def one_hot(Y, maxExpected):
    one_hot_Y = np.zeros((Y.size, maxExpected + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

## find the index of most probable number guessed by network
def get_predictions(A2):
    return np.argmax(A2, 0)

## find ratio of correct predictions to all data
def get_accuracy(predictions, Y):
    # prin1(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [29]:
myn.output_layer.weights

array([[ 0.17576027,  0.12584528,  0.41712734, -0.41873679, -0.0239657 ,
        -0.40661519, -0.1155656 , -0.47483832, -0.25291873, -0.10402701,
        -0.1513087 ,  0.41713416,  0.35169556,  0.14810189, -0.41940541,
        -0.39088118,  0.10618661,  0.27495659, -0.31353846,  0.05885413,
         0.35885739,  0.35509614, -0.2144875 , -0.07963398,  0.11744041,
        -0.0771674 ,  0.00309145,  0.43626009,  0.39287381,  0.28601095,
        -0.17266099,  0.24595993,  0.19003903,  0.33790799, -0.07855008,
        -0.27269725, -0.2956351 ,  0.36339629, -0.1456029 ,  0.03635656,
        -0.32612996,  0.42041072,  0.40678625, -0.4390187 ,  0.25427817,
        -0.32500696, -0.46669292, -0.18739201, -0.35526249, -0.42325394,
         0.27060743, -0.28038394, -0.12636718, -0.06005911, -0.18440635,
        -0.3789649 , -0.05909097,  0.33883287, -0.01843789,  0.00760644,
         0.22843197,  0.31024526, -0.31006131, -0.42970735,  0.01385904,
        -0.35876523,  0.19537079, -0.07758074, -0.2

In [30]:
Y_train_oneHot

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
        1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
        0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
        1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
        0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       

In [32]:
# accuracySum = 0
# runCount = 0

telementary = 0

lastWeights = myn.output_layer.weights

dataLen = len(X_train)

maxIt = 4500
for it in range(maxIt):
    Y_train_oneHot = one_hot(Y_train, maxExpected=1)
    predictedRAW = myn.backward_prop(input_values=(X_train), trueOutput=Y_train_oneHot)

    if(it % 50 == 0):
        print("iterations =", it)
        predictions = get_predictions(predictedRAW[0][0])
        print("Accuracy =", get_accuracy(predictions, Y_train))

iterations = 0
Accuracy = 0.9714285714285714
iterations = 50
Accuracy = 0.9714285714285714
iterations = 100
Accuracy = 0.9714285714285714
iterations = 150
Accuracy = 0.9714285714285714
iterations = 200
Accuracy = 0.9714285714285714
iterations = 250
Accuracy = 0.9714285714285714
iterations = 300
Accuracy = 0.9714285714285714
iterations = 350
Accuracy = 0.9714285714285714
iterations = 400
Accuracy = 0.9714285714285714
iterations = 450
Accuracy = 0.9714285714285714
iterations = 500
Accuracy = 0.9714285714285714
iterations = 550
Accuracy = 0.9714285714285714
iterations = 600
Accuracy = 0.9714285714285714
iterations = 650
Accuracy = 0.9714285714285714
iterations = 700
Accuracy = 0.9714285714285714
iterations = 750
Accuracy = 0.9714285714285714
iterations = 800
Accuracy = 0.9714285714285714
iterations = 850
Accuracy = 0.9714285714285714
iterations = 900
Accuracy = 0.9714285714285714
iterations = 950
Accuracy = 0.9714285714285714
iterations = 1000
Accuracy = 0.9714285714285714
iterations = 10